### PR TITLE
Fix client null pointer

### PR DESCRIPTION
**Pull request by weingithub**
make simple_client and simple_server work well

### CODE REVIEW

**Comment by weingithub** [comment]
I understand why swif_rlc_build_repair_symbol method call calloc for new_buf，but older implementation have some error, an I fix it in this merge. it is work ok in my machine.

**Comment by adjih** [comment]
Reviewing your changes, but note that the decoding part has been modified (and maybe fixed) in: https://github.com/irtf-nwcrg/swif-codec/compare/master...oumaima1234:master 

EDIT: just checked - you modified other files than the decoder, so there is no conflict with https://github.com/oumaima1234/swif-codec/tree/master  
In general, you may wish to update your email (with "git rebase"), at least to something like weingithub@github, so that people can identify the modifications and their logic, from the contributor name.

**Comment by weingithub** [comment]
@adjih 
I am sorry, but I didn't get it , why I can't see `master...oumaima1234:master` commits in master??

**Comment by oumaima1234** [comment]
@weingithub
Hello, yes, the code is in progress but I'm going to do the merge later.

**Comment by adjih** [comment]
@weingithub 
Thank you for the updates. Will merge.
For the code @oumaima1234 , it is in @oumaima1234 github repository, not yet merged. It will be (is necessary for the decoder).

**Comment by weingithub** [comment]
@oumaima1234 I got it, thanks!
@adjih  thanks

**Pull request merged**
